#!/usr/bin/env node

'use strict';

var commander = require('commander');
var chalk     = require('chalk');
var debug     = require('debug')('gxclient:cli');
var pkg       = require('../package.json');
var GXClient = require('../dist/index.js').GXClient;

var client = new GXClient();

if (process.argv.indexOf('-v') > -1) {
    console.log(pkg.version);
    process.exit(0);
}

commander.version(pkg.version)
    .option('-v --version', 'print gxclient version')
    .usage('[cmd] app');


const MSG_PREFIX = chalk.green('[GXClient]');

function displayUsage() {
    console.log('');
    console.log(chalk.green('[USAGE]'),': gxclient [options] <command>')
    console.log('');
    console.log('gxclient -h, --help             all available commands and options');
    console.log('gxclient examples               display gxclient usage examples');
    console.log('gxclient <command> -h           help on a specific command');
    console.log('');
}

function displayExamples() {
    console.log('- Generate key pairs:')
    console.log('');
    console.log(chalk.cyan('  $ gxclient generateKey'));
    console.log('');
    console.log('- Register an account:');
    console.log('');
    console.log(chalk.cyan('  $ gxclient register my-account GXC5XPhC4ZqxmqVAhwphbBMahpu1KPJb22KeQMpYFBHB14EF76tsx'));
    console.log('');
    console.log('- Import key:');
    console.log('');
    console.log(chalk.cyan('  $ gxclient import 5JDmLpBA4zHHiWpx2YCNGJBaZXE1aaZRjbuHFBR6hrMjvCQCepr 1.2.1'));
    console.log('');
    console.log('- Account API:');
    console.log('');
    console.log(chalk.cyan('  $ gxclient get_account gxchain-test-account'));
    console.log(chalk.cyan('  $ gxclient get_account_balances gxchain-test-account'));
    console.log('');
    console.log('- Asset API:');
    console.log('');
    console.log(chalk.cyan('  $ gxclient get_asset gxs'));
    console.log('');
    console.log('- Block API:');
    console.log('');
    console.log(chalk.cyan('  $ gxclient get_block 100'));
    console.log('');
    console.log('- Transfer API :');
    console.log('');
    console.log(chalk.cyan('  $ gxclient transfer gxb123 10 GXS "Hi There"'));
    console.log('');
    console.log('Check the full documentation on https://github.com/gxchain/gxclient-node');
    console.log('');
}

commander.command('examples')
  .description('display gxclient usage examples')
  .action(() => {
    console.log(MSG_PREFIX + chalk.grey(' usage examples:\n'));
    displayExamples();
    process.exit(1);
  })


//
// Catch all
//
commander.command('*')
    .action(function() {
        console.log(MSG_PREFIX + 'Command not found\n');
        displayUsage();
        // Check if it does not forget to close fds from RPC
        process.exit(1);
    });

//
// Display help if 0 arguments passed to pm2
//
if (process.argv.length == 2) {
    commander.parse(process.argv);
    displayUsage();
    // Check if it does not forget to close fds from RPC
    process.exit(1);
}
